# SPDX-FileCopyrightText: The Gommitlint Action Authors
#
# SPDX-License-Identifier: CC0-1.0
style: ""
template: CHANGELOG.tpl
info:
  title: CHANGELOG
  repository_url: https://github.com/itiquette/gommitlint-action
options:
  tag_filter_pattern: '^v'
  sort: semver
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - docs
        - style
        - test
        - build
        - ci
        - chore
        - sec
        - security
        - revert
    sort_by: Scope
  commit_groups:
    group_by: Type
    sort_by: Title
    title_order:
      - feat
      - fix
      - sec
      - security
      - perf
      - refactor
      - docs
      - test
      - build
      - ci
      - chore
      - revert
    title_maps:
      feat: Features
      fix: Bug Fixes
      sec: Security
      security: Security
      perf: Performance
      refactor: Refactor
      docs: Documentation
      style: Styling
      test: Testing
      build: Build
      ci: CI
      chore: Other
      revert: Revert
  header:
    pattern: "^(\\w*)(?:\\(([\\w$\\.\\-\\*\\s]*)\\))?!?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
